### ISSUE TITLE
Form doesn't show up

### ISSUE THREAD

**Issue by krebbi** [wardhache/community_store_reviews#3]
could you give me a hint how I get the review form?
![bildschirmfoto 2017-08-28 um 18 05 26](https://user-images.githubusercontent.com/3884521/29782093-8dbdb1ea-8c1b-11e7-94ce-02e9ea48ac95.png)
![bildschirmfoto 2017-08-28 um 18 01 13](https://user-images.githubusercontent.com/3884521/29782106-92bd1762-8c1b-11e7-93e9-7b1d3463b308.png)

**Comment by wardhache** [comment]
Krebbi,

This is due to the rights of the user groups who may see the review form.
If you go to your Dashboard, and then to Store - Settings - Reviews, you see a section named 'Review Form'. Here, you can choose all the user groups who may submit a review. 
Normally, check 'Registered Users' to make it work for you. If you check 'Guest', everyone has the ability to submit a review.
![screen shot 2017-08-28 at 22 59 16](https://user-images.githubusercontent.com/23256045/29794199-42728996-8c47-11e7-83aa-5d95eae219a0.png)

I made some slight changes to this package that you instantly can fetch without updating the package itself. In #4 I made sure the layout of the 'Review'-block is still full width when you are in a user group that may not submit a review. I made some slight changes to approving or declining reviews as well. Only users who are in the group Administrators may do that. The buttons on the Dashboard-page 'Reviews' now will disappear when the user is not part of that user group. So make yourself Administrator if you wish to approve or decline reviews.

I hope you enjoy the package, and good luck!

wardhache - webhapp

**Comment by krebbi** [comment]
thx
